# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: RetopoFlow Documentation
email: support@cgcookiemarkets.com
description: > # this means to ignore newlines until "baseurl:"
  RetopoFlow brings an extensive set of powerful retopology tools to Blender for 3D modeling and sculpting.
baseurl: "/retopoflow-docs" # the subpath of your site, e.g. /blog
url: "http://cgcookie.github.io/retopoflow-docs" # the base hostname & protocol for your site
twitter_username: carter2422
github_username:  cgcookie
copyright: "&copy 2016 CG Cookie Inc"

# Build settings
markdown: kramdown

# Category settings
category-list: [tools, tips]